# Generated by Django 3.2.12 on 2022-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionElab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_html',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_language',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
