# Generated by Django 3.2.12 on 2022-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionElab', '0002_auto_20220411_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_language',
            field=models.CharField(max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Question'),
        ),
    ]
