# Generated by Django 3.2.12 on 2022-04-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionElab', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_token',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionElab.profile'),
        ),
    ]
