# Generated by Django 3.2.12 on 2022-06-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionElab', '0006_auto_20220419_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_condition',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
